"use client";

import React, { createContext, useContext, useState, ReactNode } from "react";

export type Language = "en" | "hi" | "ta" | "te";

export const LANGUAGE_NAMES: Record<Language, string> = {
    en: "English",
    hi: "हिंदी",
    ta: "தமிழ்",
    te: "తెలుగు",
};

export type TranslationKey =
    | "nav_home" | "nav_track" | "nav_admin" | "nav_chief" | "nav_login" | "nav_logout"
    | "home_title" | "home_subtitle" | "home_form_title"
    | "form_subject" | "form_subject_placeholder"
    | "form_description" | "form_description_placeholder"
    | "form_location" | "form_location_placeholder"
    | "form_submit" | "form_submitting"
    | "form_voice_start" | "form_voice_stop" | "form_voice_listening"
    | "form_photo_analyze" | "form_photo_analyzing"
    | "track_title" | "track_subtitle" | "track_placeholder" | "track_btn"
    | "track_not_found" | "track_not_found_desc" | "track_timeline"
    | "track_progress" | "track_submit_another" | "track_priority"
    | "chat_placeholder" | "chat_title" | "chat_greeting"
    | "map_title" | "map_subtitle"
    | "feature_triage_title" | "feature_triage_desc"
    | "feature_priority_title" | "feature_priority_desc"
    | "feature_gps_title" | "feature_gps_desc"
    | "success_registered" | "success_tracking_id" | "success_category"
    | "btn_track_status" | "btn_new_complaint" | "btn_file_complaint"
    | "notif_title" | "notif_enable" | "notif_enabled"
    | "admin_title" | "admin_subtitle" | "admin_active_officers"
    | "admin_total" | "admin_pending" | "admin_in_progress" | "admin_resolved"
    | "admin_col_id" | "admin_col_subject" | "admin_col_citizen" | "admin_col_priority"
    | "admin_col_status" | "admin_col_attachments" | "admin_col_actions"
    | "admin_resolve" | "admin_done"
    | "login_welcome" | "login_select_role" | "login_email" | "login_password"
    | "login_signing_in" | "login_sign_in_as" | "login_error_role" | "login_error_creds"
    | "login_citizen_label" | "login_citizen_desc"
    | "login_authority_label" | "login_authority_desc"
    | "login_chief_label" | "login_chief_desc"
    | "chief_title" | "chief_subtitle" | "chief_export_pdf"
    | "chief_total" | "chief_pending" | "chief_in_progress" | "chief_resolved" | "chief_critical"
    | "chief_category_breakdown" | "chief_authority_status"
    | "chief_all_grievances" | "chief_complaints_total"
    | "chief_col_id" | "chief_col_subject" | "chief_col_citizen" | "chief_col_location"
    | "chief_col_priority" | "chief_col_status" | "chief_col_date"
    | "chief_active" | "chief_busy" | "chief_available" | "chief_active_cases"
    | "status_pending" | "status_in_progress" | "status_resolved"
    | "priority_critical" | "priority_high" | "priority_medium" | "priority_low";

type Translations = Record<TranslationKey, string>;

const translations: Record<Language, Translations> = {
    en: {
        nav_home: "File Complaint",
        nav_track: "Track",
        nav_admin: "Admin",
        nav_chief: "Chief",
        nav_login: "Login",
        nav_logout: "Logout",
        home_title: "Voice Your Concerns, Empowered by AI",
        home_subtitle: "Our AI-driven system ensures your complaints are heard, categorized, and prioritized with precision.",
        home_form_title: "File a Grievance",
        form_subject: "Subject",
        form_subject_placeholder: "What is this regarding?",
        form_description: "Detailed Description",
        form_description_placeholder: "Explain the issue in detail...",
        form_location: "📍 Location & Photo Evidence",
        form_location_placeholder: "City, District, or Landmark — or use GPS Camera below",
        form_submit: "Submit Grievance",
        form_submitting: "Processing with AI…",
        form_voice_start: "🎙️ Voice Input",
        form_voice_stop: "⏹️ Stop Recording",
        form_voice_listening: "🔴 Listening...",
        form_photo_analyze: "🔍 AI Analyze Photo",
        form_photo_analyzing: "⏳ Analyzing...",
        track_title: "Track Your Grievance",
        track_subtitle: "Enter your Tracking ID to view the real-time status and progress of your complaint.",
        track_placeholder: "e.g. GRV-12044",
        track_btn: "Track →",
        track_not_found: "Complaint Not Found",
        track_timeline: "📅 Complaint Timeline",
        chat_placeholder: "Ask anything about filing a complaint...",
        chat_title: "AI Assistant",
        chat_greeting: "👋 Hi! I'm your AI grievance assistant. How can I help you today? Try asking:\n• How do I file a water complaint?\n• What is my complaint status?\n• How long does resolution take?",
        map_title: "🗺️ Live Complaint Map",
        map_subtitle: "View all active complaints across the city in real time.",
        feature_triage_title: "Instant Triage",
        feature_triage_desc: "AI analyzes your text to identify the right department and urgency level automatically.",
        feature_priority_title: "Fair Prioritization",
        feature_priority_desc: "Critical issues like health and safety are flagged instantly for immediate action.",
        feature_gps_title: "GPS Photo Evidence",
        feature_gps_desc: "Capture photos stamped with GPS coordinates and timestamp — undeniable evidence.",
        success_registered: "Complaint Registered",
        success_tracking_id: "Tracking ID:",
        success_category: "Category:",
        btn_track_status: "🔍 Track Status",
        btn_new_complaint: "+ New Complaint",
        btn_file_complaint: "File a New Complaint",
        notif_title: "Status Update",
        notif_enable: "🔔 Enable Notifications",
        notif_enabled: "🔔 Notifications On",
        track_not_found_desc: "No complaint found for this ID. Please double-check your Tracking ID.",
        track_progress: "Resolution Progress",
        track_submit_another: "Submit Another Complaint",
        track_priority: "Priority",
        admin_title: "Admin Command Center",
        admin_subtitle: "Overseeing AI-Triaged Grievances & Resolution Workflows",
        admin_active_officers: "🟢 4 Active Officers",
        admin_total: "Total",
        admin_pending: "Pending",
        admin_in_progress: "In Progress",
        admin_resolved: "Resolved",
        admin_col_id: "ID",
        admin_col_subject: "Subject & Category",
        admin_col_citizen: "Citizen",
        admin_col_priority: "Priority",
        admin_col_status: "Status",
        admin_col_attachments: "Attachments",
        admin_col_actions: "Actions",
        admin_resolve: "✓ Resolve",
        admin_done: "✓ Done",
        login_welcome: "Welcome to",
        login_select_role: "Select your role to continue",
        login_email: "Email",
        login_password: "Password",
        login_signing_in: "Signing in...",
        login_sign_in_as: "Sign in as",
        login_error_role: "Please select a role first.",
        login_error_creds: "Invalid credentials. Check the hint below each role card.",
        login_citizen_label: "Citizen User",
        login_citizen_desc: "File & track your grievances",
        login_authority_label: "Authority Officer",
        login_authority_desc: "Manage & resolve complaints",
        login_chief_label: "Chief Admin",
        login_chief_desc: "System-wide oversight & analytics",
        chief_title: "Chief Command Center",
        chief_subtitle: "System-wide analytics, grievance oversight, and authority management",
        chief_export_pdf: "📄 Export PDF Report",
        chief_total: "Total Grievances",
        chief_pending: "Pending",
        chief_in_progress: "In Progress",
        chief_resolved: "Resolved",
        chief_critical: "Critical",
        chief_category_breakdown: "📊 Category Breakdown",
        chief_authority_status: "🏗️ Authority Status",
        chief_all_grievances: "🗂️ All System Grievances",
        chief_complaints_total: "complaints total",
        chief_col_id: "ID",
        chief_col_subject: "Subject & Category",
        chief_col_citizen: "Citizen",
        chief_col_location: "Location",
        chief_col_priority: "Priority",
        chief_col_status: "Status",
        chief_col_date: "Date",
        chief_active: "Active",
        chief_busy: "Busy",
        chief_available: "Available",
        chief_active_cases: "active",
        status_pending: "Pending",
        status_in_progress: "In Progress",
        status_resolved: "Resolved",
        priority_critical: "Critical",
        priority_high: "High",
        priority_medium: "Medium",
        priority_low: "Low",
    },
    hi: {
        nav_home: "शिकायत दर्ज करें",
        nav_track: "ट्रैक करें",
        nav_admin: "व्यवस्थापक",
        nav_chief: "मुख्य",
        nav_login: "लॉगिन",
        nav_logout: "लॉगआउट",
        home_title: "अपनी बात कहें, AI की शक्ति से",
        home_subtitle: "हमारी AI प्रणाली आपकी शिकायतों को सुनती, वर्गीकृत करती और प्राथमिकता देती है।",
        home_form_title: "शिकायत दर्ज करें",
        form_subject: "विषय",
        form_subject_placeholder: "यह किस बारे में है?",
        form_description: "विस्तृत विवरण",
        form_description_placeholder: "समस्या को विस्तार से बताएं...",
        form_location: "📍 स्थान और फोटो प्रमाण",
        form_location_placeholder: "शहर, जिला, या स्थान",
        form_submit: "शिकायत जमा करें",
        form_submitting: "AI प्रसंस्करण...",
        form_voice_start: "🎙️ आवाज़ से दर्ज करें",
        form_voice_stop: "⏹️ रिकॉर्डिंग बंद करें",
        form_voice_listening: "🔴 सुन रहा है...",
        form_photo_analyze: "🔍 AI फोटो विश्लेषण",
        form_photo_analyzing: "⏳ विश्लेषण हो रहा है...",
        track_title: "अपनी शिकायत ट्रैक करें",
        track_subtitle: "अपनी शिकायत की स्थिति देखने के लिए ट्रैकिंग आईडी दर्ज करें।",
        track_placeholder: "जैसे GRV-12044",
        track_btn: "ट्रैक करें →",
        track_not_found: "शिकायत नहीं मिली",
        track_timeline: "📅 शिकायत की समयरेखा",
        chat_placeholder: "शिकायत के बारे में कुछ भी पूछें...",
        chat_title: "AI सहायक",
        chat_greeting: "👋 नमस्ते! मैं आपका AI शिकायत सहायक हूं। आज मैं आपकी कैसे मदद कर सकता हूं?",
        map_title: "🗺️ लाइव शिकायत मानचित्र",
        map_subtitle: "शहर भर की सक्रिय शिकायतें रीयल टाइम में देखें।",
        feature_triage_title: "तत्काल वर्गीकरण",
        feature_triage_desc: "AI आपके पाठ का विश्लेषण करके सही विभाग और तात्कालिकता स्तर निर्धारित करता है।",
        feature_priority_title: "उचित प्राथमिकता",
        feature_priority_desc: "स्वास्थ्य और सुरक्षा जैसी गंभीर समस्याओं को तत्काल चिह्नित किया जाता है।",
        feature_gps_title: "GPS फोटो प्रमाण",
        feature_gps_desc: "GPS निर्देशांक और टाइमस्टैम्प के साथ फ़ोटो कैप्चर करें।",
        success_registered: "शिकायत दर्ज हो गई",
        success_tracking_id: "ट्रैकिंग आईडी:",
        success_category: "श्रेणी:",
        btn_track_status: "🔍 स्थिति ट्रैक करें",
        btn_new_complaint: "+ नई शिकायत",
        btn_file_complaint: "नई शिकायत दर्ज करें",
        notif_title: "स्थिति अपडेट",
        notif_enable: "🔔 सूचनाएं चालू करें",
        notif_enabled: "🔔 सूचनाएं चालू हैं",
        track_not_found_desc: "इस ID से कोई शिकायत नहीं मिली। कृपया अपनी ट्रैकिंग ID दोबारा जांचें।",
        track_progress: "समाधान की प्रगति",
        track_submit_another: "एक और शिकायत दर्ज करें",
        track_priority: "प्राथमिकता",
        admin_title: "प्रशासन केंद्र",
        admin_subtitle: "AI वर्गीकृत शिकायतों और प्रक्रियाओं की निगरानी",
        admin_active_officers: "🟢 4 सक्रिय अधिकारी",
        admin_total: "कुल",
        admin_pending: "लंबित",
        admin_in_progress: "प्रगति में",
        admin_resolved: "हल हुई",
        admin_col_id: "आईडी",
        admin_col_subject: "विषय एवं श्रेणी",
        admin_col_citizen: "नागरिक",
        admin_col_priority: "प्राथमिकता",
        admin_col_status: "स्थिति",
        admin_col_attachments: "संलग्नक",
        admin_col_actions: "कार्रवाई",
        admin_resolve: "✓ हल करें",
        admin_done: "✓ हो गया",
        login_welcome: "में आपका स्वागत है",
        login_select_role: "जारी रखने के लिए अपनी भूमिका चुनें",
        login_email: "ईमेल",
        login_password: "पासवर्ड",
        login_signing_in: "साइन इन हो रहा है...",
        login_sign_in_as: "साइन इन करें",
        login_error_role: "कृपया पहले एक भूमिका चुनें।",
        login_error_creds: "अमान्य क्रेडेंशियल। कृपया संकेत जांचें।",
        login_citizen_label: "नागरिक उपयोगकर्ता",
        login_citizen_desc: "शिकायत दर्ज करें और ट्रैक करें",
        login_authority_label: "प्राधिकरण अधिकारी",
        login_authority_desc: "शिकायतें प्रबंधित करें और हल करें",
        login_chief_label: "मुख्य प्रशासक",
        login_chief_desc: "प्रणाली-व्यापी निगरानी और विश्लेषण",
        chief_title: "मुख्य कमांड सेंटर",
        chief_subtitle: "सिस्टम-व्यापी विश्लेषण, शिकायत निगरानी और प्राधिकरण प्रबंधन",
        chief_export_pdf: "📄 PDF रिपोर्ट निर्यात करें",
        chief_total: "कुल शिकायतें",
        chief_pending: "लंबित",
        chief_in_progress: "प्रगति में",
        chief_resolved: "हल हुई",
        chief_critical: "गंभीर",
        chief_category_breakdown: "📊 श्रेणी विवरण",
        chief_authority_status: "🏛️ प्राधिकरण स्थिति",
        chief_all_grievances: "🗂️ सभी शिकायतें",
        chief_complaints_total: "शिकायतें कुल",
        chief_col_id: "आईडी",
        chief_col_subject: "विषय एवं श्रेणी",
        chief_col_citizen: "नागरिक",
        chief_col_location: "स्थान",
        chief_col_priority: "प्राथमिकता",
        chief_col_status: "स्थिति",
        chief_col_date: "तारीख",
        chief_active: "सक्रिय",
        chief_busy: "व्यस्त",
        chief_available: "उपलब्ध",
        chief_active_cases: "सक्रिय",
        status_pending: "लंबित",
        status_in_progress: "प्रगति में",
        status_resolved: "हल हुई",
        priority_critical: "गंभीर",
        priority_high: "उच्च",
        priority_medium: "मध्यम",
        priority_low: "निम्न",
    },
    ta: {
        nav_home: "புகார் பதிவு",
        nav_track: "கண்காணி",
        nav_admin: "நிர்வாகி",
        nav_chief: "தலைமை",
        nav_login: "உள்நுழை",
        nav_logout: "வெளியேறு",
        home_title: "உங்கள் குரலை எழுப்புங்கள், AI ஆற்றலுடன்",
        home_subtitle: "எங்கள் AI அமைப்பு உங்கள் புகார்களை கேட்டு, வகைப்படுத்தி, முன்னுரிமை அளிக்கிறது.",
        home_form_title: "புகார் தாக்கல் செய்யுங்கள்",
        form_subject: "தலைப்பு",
        form_subject_placeholder: "இது எதைப் பற்றியது?",
        form_description: "விரிவான விவரம்",
        form_description_placeholder: "பிரச்சினையை விரிவாக விளக்குங்கள்...",
        form_location: "📍 இடம் மற்றும் புகைப்பட சான்று",
        form_location_placeholder: "நகரம், மாவட்டம் அல்லது இடம்",
        form_submit: "புகாரை சமர்ப்பிக்க",
        form_submitting: "AI செயல்படுகிறது…",
        form_voice_start: "🎙️ குரல் உள்ளீடு",
        form_voice_stop: "⏹️ பதிவை நிறுத்து",
        form_voice_listening: "🔴 கேட்கிறது...",
        form_photo_analyze: "🔍 AI புகைப்பட பகுப்பாய்வு",
        form_photo_analyzing: "⏳ பகுப்பாய்வு செய்கிறது...",
        track_title: "உங்கள் புகாரை கண்காணிக்கவும்",
        track_subtitle: "உங்கள் புகாரின் நிலையை பார்க்க கண்காணிப்பு ID ஐ உள்ளிடுங்கள்.",
        track_placeholder: "எ.கா. GRV-12044",
        track_btn: "கண்காணி →",
        track_not_found: "புகார் கிடைக்கவில்லை",
        track_timeline: "📅 புகார் காலவரிசை",
        chat_placeholder: "புகார் பதிவு பற்றி எதையும் கேளுங்கள்...",
        chat_title: "AI உதவியாளர்",
        chat_greeting: "👋 வணக்கம்! நான் உங்கள் AI புகார் உதவியாளர். இன்று நான் உங்களுக்கு எவ்வாறு உதவ முடியும்?",
        map_title: "🗺️ நேரடி புகார் வரைபடம்",
        map_subtitle: "நகரம் முழுவதும் உள்ள சுறுசுறுப்பான புகார்களை நேரடியாக பார்க்கவும்.",
        feature_triage_title: "உடனடி வகைப்பாடு",
        feature_triage_desc: "AI உங்கள் உரையை பகுப்பாய்வு செய்து சரியான துறை மற்றும் அவசரநிலையை தீர்மானிக்கிறது.",
        feature_priority_title: "நியாயமான முன்னுரிமை",
        feature_priority_desc: "சுகாதாரம் மற்றும் பாதுகாப்பு போன்ற முக்கியமான சிக்கல்கள் உடனடியாக கொடியிடப்படும்.",
        feature_gps_title: "GPS புகைப்பட சான்று",
        feature_gps_desc: "GPS ஆயத்தொகுப்புகள் மற்றும் நேரமுத்திரையுடன் புகைப்படங்களை பதிவுசெய்யுங்கள்.",
        success_registered: "புகார் பதிவு செய்யப்பட்டது",
        success_tracking_id: "கண்காணிப்பு ID:",
        success_category: "வகை:",
        btn_track_status: "🔍 நிலையை கண்காணி",
        btn_new_complaint: "+ புதிய புகார்",
        btn_file_complaint: "புதிய புகார் பதிவு",
        notif_title: "நிலை புதுப்பிப்பு",
        notif_enable: "🔔 அறிவிப்புகளை இயக்கு",
        notif_enabled: "🔔 அறிவிப்புகள் இயக்கப்பட்டுள்ளன",
        track_not_found_desc: "இந்த ID இல் புகார் எதுவும் காணவில்லை. கண்காணிப்பு IDஐ மீண்டும் சரிபார்க்கவும்.",
        track_progress: "தீர்வு முன்னேற்றம்",
        track_submit_another: "மற்றொரு புகாரை சமர்ப்பிக்கவும்",
        track_priority: "முன்னுரிமை",
        admin_title: "நிர்வாக கட்டளை மையம்",
        admin_subtitle: "AI வகைப்படுத்தல் மற்றும் தீர்வு பணிப்பாய்வுகளை மேற்பார்வை",
        admin_active_officers: "🟢 4 செயலில் உள்ள அதிகாரிகள்",
        admin_total: "மொத்தம்",
        admin_pending: "நிலுவையில்",
        admin_in_progress: "நடைபெறுகிறது",
        admin_resolved: "தீர்க்கப்பட்டது",
        admin_col_id: "ஐடி",
        admin_col_subject: "தலைப்பு & வகை",
        admin_col_citizen: "குடிமகன்",
        admin_col_priority: "முன்னுரிமை",
        admin_col_status: "நிலை",
        admin_col_attachments: "இணைப்புகள்",
        admin_col_actions: "செயல்கள்",
        admin_resolve: "✓ தீர்க்க",
        admin_done: "✓ முடிந்தது",
        login_welcome: "வரவேற்கிறோம்",
        login_select_role: "தொடர உங்கள் பங்கை தேர்ந்தெடுங்கள்",
        login_email: "மின்னஞ்சல்",
        login_password: "கடவுச்சொல்",
        login_signing_in: "உள்நுழைகிறது...",
        login_sign_in_as: "உள்நுழை",
        login_error_role: "முதலில் ஒரு பங்கை தேர்ந்தெடுக்கவும்.",
        login_error_creds: "தவறான நற்சான்றிதழ்கள். குறிப்பை சரிபார்க்கவும்.",
        login_citizen_label: "குடிமக்கள் பயனர்",
        login_citizen_desc: "புகார்களை பதிவு செய்து கண்காணிக்கவும்",
        login_authority_label: "அதிகாரி அலுவலர்",
        login_authority_desc: "புகார்களை நிர்வகிக்கவும் மற்றும் தீர்க்கவும்",
        login_chief_label: "தலைமை நிர்வாகி",
        login_chief_desc: "அமைப்பு அளவிலான கண்காணிப்பு & பகுப்பாய்வு",
        chief_title: "தலைமை கட்டளை மையம்",
        chief_subtitle: "அமைப்பு அளவிலான பகுப்பாய்வு, புகார் மேற்பார்வை மற்றும் அதிகார நிர்வகம்",
        chief_export_pdf: "📄 PDF முதல் ஏற்றுமதி செய்",
        chief_total: "மொத்த புகார்கள்",
        chief_pending: "நிலுவையில்",
        chief_in_progress: "நடைபெறுகிறது",
        chief_resolved: "தீர்க்கப்பட்டது",
        chief_critical: "குரிப்பிட்டம்",
        chief_category_breakdown: "📊 வகை பகுப்பு",
        chief_authority_status: "🏗️ அதிகார நிலை",
        chief_all_grievances: "🗂️ அனைத்து புகார்கள்",
        chief_complaints_total: "மொத்த புகார்கள்",
        chief_col_id: "ஐடி",
        chief_col_subject: "தலைப்பு & வகை",
        chief_col_citizen: "குடிமகன்",
        chief_col_location: "இடம்",
        chief_col_priority: "முன்னுரிமை",
        chief_col_status: "நிலை",
        chief_col_date: "தேதி",
        chief_active: "செயலில்",
        chief_busy: "முடிப்பு",
        chief_available: "கிடைக்கிறது",
        chief_active_cases: "செயலில்",
        status_pending: "நிலுவையில்",
        status_in_progress: "நடைபெறுகிறது",
        status_resolved: "தீர்க்கப்பட்டது",
        priority_critical: "குரிப்பிட்டம்",
        priority_high: "உயர்வு",
        priority_medium: "மத்திமம்",
        priority_low: "தாழ்வு",
    },
    te: {
        nav_home: "ఫిర్యాదు నమోదు",
        nav_track: "ట్రాక్",
        nav_admin: "అడ్మిన్",
        nav_chief: "చీఫ్",
        nav_login: "లాగిన్",
        nav_logout: "లాగ్అవుట్",
        home_title: "మీ సమస్యలు చెప్పండి, AI శక్తితో",
        home_subtitle: "మా AI వ్యవస్థ మీ ఫిర్యాదులను వినడం, వర్గీకరించడం మరియు ప్రాధాన్యత ఇవ్వడం చేస్తుంది.",
        home_form_title: "ఫిర్యాదు నమోదు చేయండి",
        form_subject: "విషయం",
        form_subject_placeholder: "ఇది దేని గురించి?",
        form_description: "వివరాల వివరణ",
        form_description_placeholder: "సమస్యను వివరంగా వివరించండి...",
        form_location: "📍 స్థానం మరియు ఫోటో ఆధారం",
        form_location_placeholder: "నగరం, జిల్లా లేదా ల్యాండ్‌మార్క్",
        form_submit: "ఫిర్యాదు సమర్పించండి",
        form_submitting: "AI ప్రాసెస్ చేస్తోంది…",
        form_voice_start: "🎙️ వాయిస్ ఇన్‌పుట్",
        form_voice_stop: "⏹️ రికార్డింగ్ ఆపు",
        form_voice_listening: "🔴 వింటోంది...",
        form_photo_analyze: "🔍 AI ఫోటో విశ్లేషణ",
        form_photo_analyzing: "⏳ విశ్లేషిస్తోంది...",
        track_title: "మీ ఫిర్యాదును ట్రాక్ చేయండి",
        track_subtitle: "మీ ఫిర్యాదు స్థితిని చూడడానికి ట్రాకింగ్ ID నమోదు చేయండి.",
        track_placeholder: "ఉదా. GRV-12044",
        track_btn: "ట్రాక్ →",
        track_not_found: "ఫిర్యాదు కనుగొనబడలేదు",
        track_timeline: "📅 ఫిర్యాదు టైమ్‌లైన్",
        chat_placeholder: "ఫిర్యాదు గురించి ఏదైనా అడగండి...",
        chat_title: "AI సహాయకుడు",
        chat_greeting: "👋 నమస్తే! నేను మీ AI ఫిర్యాదు సహాయకుడిని. ఈరోజు నేను మీకు ఎలా సహాయపడగలను?",
        map_title: "🗺️ లైవ్ ఫిర్యాదు మ్యాప్",
        map_subtitle: "నగరం అంతటా చురుకైన ఫిర్యాదులను రియల్ టైమ్‌లో చూడండి.",
        feature_triage_title: "తక్షణ వర్గీకరణ",
        feature_triage_desc: "AI మీ వచనాన్ని విశ్లేషించి సరైన విభాగం మరియు అత్యవసర స్థాయిని నిర్ణయిస్తుంది.",
        feature_priority_title: "న్యాయమైన ప్రాధాన్యత",
        feature_priority_desc: "ఆరోగ్యం మరియు భద్రత వంటి క్లిష్టమైన సమస్యలు వెంటనే గుర్తించబడతాయి.",
        feature_gps_title: "GPS ఫోటో ఆధారం",
        feature_gps_desc: "GPS కోఆర్డినేట్‌లు మరియు టైమ్‌స్టాంప్‌తో ఫోటోలు తీయండి.",
        success_registered: "ఫిర్యాదు నమోదైంది",
        success_tracking_id: "ట్రాకింగ్ ID:",
        success_category: "వర్గం:",
        btn_track_status: "🔍 స్థితి ట్రాక్",
        btn_new_complaint: "+ కొత్త ఫిర్యాదు",
        btn_file_complaint: "కొత్త ఫిర్యాదు నమోదు",
        notif_title: "స్థితి నవీకరణ",
        notif_enable: "🔔 నోటిఫికేషన్లు ఆన్ చేయి",
        notif_enabled: "🔔 నోటిఫికేషన్లు చెలవులో ఉన్నాయి",
        track_not_found_desc: "ఈ IDతో ఫిర్యాదు ఏదీ కనుగొనబడలేదు. దయచేసి మీ ట్రాకింగ్ IDని మళ్ళీ తనిఖీ చేయండి.",
        track_progress: "పరిష్కార పురోగతి",
        track_submit_another: "మరొక ఫిర్యాదు సమర్పించండి",
        track_priority: "ప్రాధాన్యత",
        admin_title: "అడ్మిన్ కమాండ్ సెంటర్",
        admin_subtitle: "AI వర్గీకరణ మరియు పరిష్కార వర్క్‌ఫ్లోలను పర్యవేక్షించడం",
        admin_active_officers: "🟢 4 చురుకైన అధికారులు",
        admin_total: "మొత్తం",
        admin_pending: "పెండింగ్",
        admin_in_progress: "పురోగతిలో",
        admin_resolved: "పరిష్కరించబడింది",
        admin_col_id: "ఐడీ",
        admin_col_subject: "విషయం & వర్గం",
        admin_col_citizen: "పౌరుడు",
        admin_col_priority: "ప్రాధాన్యత",
        admin_col_status: "స్థితి",
        admin_col_attachments: "అనుబంధాలు",
        admin_col_actions: "చర్యలు",
        admin_resolve: "✓ పరిష్కరించు",
        admin_done: "✓ పూర్తైంది",
        login_welcome: "స్వాగతం",
        login_select_role: "కొనసాగించడానికి మీ పాత్రను ఎంచుకోండి",
        login_email: "ఇమెయిల్",
        login_password: "పాస్‌వర్డ్",
        login_signing_in: "సైన్ ఇన్ అవుతోంది...",
        login_sign_in_as: "సైన్ ఇన్",
        login_error_role: "దయచేసి ముందుగా పాత్రను ఎంచుకోండి.",
        login_error_creds: "చెల్లని ధృవీకరణ పత్రాలు. సూచనను తనిఖీ చేయండి.",
        login_citizen_label: "పౌర వినియోగదారు",
        login_citizen_desc: "ఫిర్యాదులు నమోదు చేయండి & ట్రాక్ చేయండి",
        login_authority_label: "అధికార అధికారి",
        login_authority_desc: "ఫిర్యాదులు నిర్వహించండి & పరిష్కరించండి",
        login_chief_label: "చీఫ్ అడ్మిన్",
        login_chief_desc: "వ్యవస్థ-వ్యాప్త పర్యవేక్షణ & విశ్లేషణ",
        chief_title: "చీఫ్ కమాండ్ సెంటర్",
        chief_subtitle: "వ్యవస్థ-వ్యాప్త విశ్లేషణలు, ఫిర్యాదు పర్యవేక్షణ మరియు అధికార నిర్వహణ",
        chief_export_pdf: "📄 PDF నివేదిక ఎక్స్పోర్ట్",
        chief_total: "మొత్తం ఫిర్యాదులు",
        chief_pending: "పెండింగ్",
        chief_in_progress: "పురోగతిలో",
        chief_resolved: "పరిష్కరించబడింది",
        chief_critical: "క్రిటికల్",
        chief_category_breakdown: "📊 వర్గ వివరణ",
        chief_authority_status: "🏗️ అధికార స్థితి",
        chief_all_grievances: "🗂️ అన్ని ఫిర్యాదులు",
        chief_complaints_total: "మొత్తం ఫిర్యాదులు",
        chief_col_id: "ఐడీ",
        chief_col_subject: "విషయం & వర్గం",
        chief_col_citizen: "పౌరుడు",
        chief_col_location: "స్థానం",
        chief_col_priority: "ప్రాధాన్యత",
        chief_col_status: "స్థితి",
        chief_col_date: "తేదీ",
        chief_active: "చురుకు",
        chief_busy: "వ్యస్తం",
        chief_available: "అందుబాటులో",
        chief_active_cases: "చురుకు",
        status_pending: "పెండింగ్",
        status_in_progress: "పురోగతిలో",
        status_resolved: "పరిష్కరించబడింది",
        priority_critical: "క్రిటికల్",
        priority_high: "అధికం",
        priority_medium: "మధ్యమం",
        priority_low: "క్యూ",
    },
};

interface LanguageContextType {
    lang: Language;
    setLang: (lang: Language) => void;
    t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
    const [lang, setLang] = useState<Language>("en");
    const t = (key: TranslationKey) => translations[lang][key] ?? key;
    return (
        <LanguageContext.Provider value={{ lang, setLang, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLang() {
    const ctx = useContext(LanguageContext);
    if (!ctx) throw new Error("useLang must be used within LanguageProvider");
    return ctx;
}
